const EventDetails = [
  {
    key: 1,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "PAPER CRAFTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PaperCrafting",
  },
  {
    key: 2,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "CIRCUIT DESIGN",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/CircuitDesign",

  },

  {
    key: 3,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "BRIDGE DESIGN",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize:"₹ 2000",
    redirect: "/anwesh/registration/BridgeDesign",

  },
  {
    key: 4,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "QUIZ",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Quiz",

  },
  {
    key: 5,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "FUN WITH CODING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithCoding"

  },
  {
    key: 6,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "JAM",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Jam",

  },
  {
    key: 7,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "ONLINE GAMING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/OnlineGaming",

  },
  {
    key: 8,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "POSTER PAINTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PosterPainting",

  },
  {
    key: 9,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "TREASURE HUNT",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/TeasureHunt",

  },
  {
    key: 10,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "PAPER PRESENTATION",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PaperPresentation",

  },
  {
    key: 11,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "FUN WITH WELDING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithWelding",

  },
  {
    key: 12,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "RANGOLI",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Rangoli",

  },
  {
    key: 13,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "MATH OLYMPIAD",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/MathOlympiad",

  },
  {
    key: 14,
    url: "https://i.postimg.cc/1Xy5R4wq/techfest.jpg",
    name: "FACE PAINTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FacePainting",

  },
];

export default EventDetails;
