const EventDetails = [
  // {
  //   key: 1,
  //   url: "https://i.postimg.cc/6QNbS4gj/Paper-Crafting.webp",
  //   name: "PAPER CRAFTING",
  //   venue: "To be decided",
  //   date: "__ / __ / __",
  //   desc: "",
  //   EventIncharge: "Xyz",
  //   EventCoordinators: ["ABC", "XYZ", "RST"],
  //   volunteers: ["Rohan", "Mohan", "Simran"],
  //   time: "__ : __ : __",
  //   prize: "₹ 2000",
  //   redirect: "/anwesh/registration/PaperCrafting",
  // },
  
  {
    key: 2,
    url: "https://i.postimg.cc/d1jbnj0j/Circuit-Design.webp",
    name: "FUN WITH ELECTRONIC CIRCUITS",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Designing circuits by utilizing various circuit components such as diodes, resistors, capacitors, etc.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/CircuitDesign",
  },
  {
    key: 3,
    url: "https://i.postimg.cc/tJzMtq2S/Online-Gaming.webp",
    name: "SMART GAMES",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Participate in smart and strategic gaming activities",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/OnlineGaming",
  },

  {
    key: 4,
    url: "https://i.postimg.cc/PJH7wpzv/Quiz.webp",
    name: "TECH QUIZ",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Test your knowledge in a tech-oriented quiz",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Quiz",
  },
  {
    key: 5,
    url: "https://i.postimg.cc/9f2kNSb4/Coding.webp",
    name: "CODATHON",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "A coding competition to showcase programming skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithCoding",
  },
  {
    key: 6,
    url: "https://i.postimg.cc/6pnScwrJ/Jam.webp",
    name: "JAM",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Speak on a given topic for a minute without hesitation",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Jam",
  },
  {
    key: 7,
    url: "https://i.postimg.cc/pr2Ht1SS/Face-Painting.webp",
    name: "FACETHEAM",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "By using face colour ( paraffin wax based or gel based colour) for representation a theme on one's  face. A group consists of 2 persons. One person will paint other s face to Represent the theme.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FacePainting",
  },
  
  {
    key: 8,
    url: "https://i.postimg.cc/cHLjqX4b/Dimag-Ki-Batti.webp",
    name: "DIMAG KI BATI",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Represent a theme by painting on poster. Theme will be given by teacher coordinator ",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PosterPainting",
  },
  {
    key: 9,
    url: "https://i.postimg.cc/dQWRdZBM/Treasure-Hunt.webp",
    name: "TREASURE PLEASURE",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Hunt for hidden treasures in a fun adventure",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/TeasureHunt",
  },
  {
    key: 10,
    url: "https://i.postimg.cc/fRdY62hZ/Paper-Presentation.webp",
    name: "PAPER PRESENTATION",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "You will deliver a presentation on a specific topic using slides.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PaperPresentation",
  },
  {
    key: 11,
    url: "https://i.postimg.cc/s2NQx5zK/Fun-With-Welding.webp",
    name: "FUN WITH WELDING",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Students are tasked with crafting a project using welding techniques.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithWelding",
  },
  {
    key: 12,
    url: "https://i.postimg.cc/7hXKJBZj/Rangoli.webp",
    name: "FLOOR ART",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Rangoli on floor on a particular theme by using different colours.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Rangoli",
  },
  {
    key: 13,
    url: "https://i.postimg.cc/5tHDdM2y/Math-Olympiad.webp",
    name: "MATH OLYMPIA",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Challenge your mathematical prowess",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/MathOlympiad",
  },
  
  {
    key: 14,
    url: "https://i.postimg.cc/VkRMqv2y/Bridge-Design.webp",
    name: "BRIDGE ARCHITECTS",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "Constructing a bridge utilizing various building components as suggested by your teacher.",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/BridgeDesign",
  },
];

export default EventDetails;
