const EventDetails = [
  {
    key: 1,
    url: "https://i.postimg.cc/6QNbS4gj/Paper-Crafting.webp",
    name: "PAPER CRAFTING",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PaperCrafting",
  },
  {
    key: 2,
    url: "https://i.postimg.cc/d1jbnj0j/Circuit-Design.webp",
    name: "FUN WITH ELECTRONIC CIRCUITS",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/CircuitDesign",
  },
  {
    key: 3,
    url: "https://i.postimg.cc/tJzMtq2S/Online-Gaming.webp",
    name: "SMART GAMES",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/OnlineGaming",
  },

  {
    key: 4,
    url: "https://i.postimg.cc/PJH7wpzv/Quiz.webp",
    name: "TECH QUIZ",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Quiz",
  },
  {
    key: 5,
    url: "https://i.postimg.cc/9f2kNSb4/Coding.webp",
    name: "CODATHON",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithCoding",
  },
  {
    key: 6,
    url: "https://i.postimg.cc/6pnScwrJ/Jam.webp",
    name: "JAM",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Jam",
  },
  {
    key: 7,
    url: "https://i.postimg.cc/pr2Ht1SS/Face-Painting.webp",
    name: "FACETHEAM",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FacePainting",
  },
  
  {
    key: 8,
    url: "https://i.postimg.cc/TY7kRHSD/Poster-Painting.webp",
    name: "DIMAG KI BATI",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PosterPainting",
  },
  {
    key: 9,
    url: "https://i.postimg.cc/dQWRdZBM/Treasure-Hunt.webp",
    name: "TREASURE PLEASURE",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/TeasureHunt",
  },
  {
    key: 10,
    url: "https://i.postimg.cc/fRdY62hZ/Paper-Presentation.webp",
    name: "PAPER PRESENTATION",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/PaperPresentation",
  },
  {
    key: 11,
    url: "https://i.postimg.cc/s2NQx5zK/Fun-With-Welding.webp",
    name: "FUN WITH WELDING",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/FunWithWelding",
  },
  {
    key: 12,
    url: "https://i.postimg.cc/7hXKJBZj/Rangoli.webp",
    name: "FLOOR ART",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/Rangoli",
  },
  {
    key: 13,
    url: "https://i.postimg.cc/5tHDdM2y/Math-Olympiad.webp",
    name: "MATH OLYMPIA",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/MathOlympiad",
  },
  
  {
    key: 14,
    url: "https://i.postimg.cc/VkRMqv2y/Bridge-Design.webp",
    name: "BRIDGE ARCHITECTS",
    venue: "To be decided",
    date: "__ / __ / __",
    desc: "",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "__ : __ : __",
    prize: "₹ 2000",
    redirect: "/anwesh/registration/BridgeDesign",
  },
];

export default EventDetails;
